# Generated by Django 5.0 on 2023-12-23 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStorageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Kirim'), ('export', 'Chiqim'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('cancel', 'Bekor qilish'), ('sold', 'Sotish')], max_length=6)),
                ('details', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(default="O'chirilgan foydalanuvchi", on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('amount_type', models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('point', 'Dona')], max_length=5)),
                ('price', models.CharField(default=0, max_length=600)),
                ('confirmed_price', models.CharField(default=0, max_length=600)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=3)),
                ('is_active', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('pending', 'Kutilmoqda')], default='pending', max_length=8)),
                ('import_comment', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.materialtype')),
            ],
        ),
    ]
