# Generated by Django 5.0 on 2023-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialstorage_amount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='import_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
