# Generated by Django 5.0 on 2023-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materialstorage_import_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='amount_type',
            field=models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('kg', 'Kilogramm'), ('point', 'Dona'), ('meter', 'Metr')], max_length=5),
        ),
    ]
