# Generated by Django 5.0 on 2023-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materialstorage_amount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialstoragehistory',
            name='details',
        ),
        migrations.AddField(
            model_name='materialstoragehistory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialstoragehistory',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='materialstoragehistory',
            name='price_type',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=5),
        ),
        migrations.AddField(
            model_name='materialstoragehistory',
            name='where',
            field=models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('production', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16),
        ),
    ]
