# Generated by Django 5.0 on 2023-12-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_materialstorage_confirmed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstoragehistory',
            name='action',
            field=models.CharField(choices=[('import', 'Kirim'), ('export', 'Chiqim'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('cancel', 'Bekor qilish'), ('sold', 'Sotish'), ('confirm', 'Tasdiqlash')], max_length=9),
        ),
    ]
