# Generated by Django 5.0 on 2023-12-24 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialstoragehistory_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpareStorageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Kirim'), ('export', 'Chiqim'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('cancel', 'Bekor qilish'), ('sold', 'Sotish'), ('confirm', 'Tasdiqlash')], max_length=9)),
                ('amount', models.IntegerField(default=0)),
                ('amount_type', models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('kg', 'Kilogramm'), ('point', 'Dona'), ('meter', 'Metr')], default='meter', max_length=5)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=5)),
                ('where', models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('production', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.sparetype')),
            ],
        ),
        migrations.CreateModel(
            name='SpareStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('amount_type', models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('kg', 'Kilogramm'), ('point', 'Dona'), ('meter', 'Metr')], default='meter', max_length=16)),
                ('price', models.CharField(default=0, max_length=600)),
                ('confirmed_price', models.CharField(default=0, max_length=600)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=3)),
                ('is_active', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('pending', 'Kutilmoqda')], default='pending', max_length=8)),
                ('import_comment', models.CharField(max_length=255)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.sparetype')),
            ],
        ),
    ]
