# Generated by Django 5.0 on 2023-12-24 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_sparetype_sparestoragehistory_sparestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparestorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparestorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
