# Generated by Django 5.0 on 2023-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_sparestorage_created_at_sparestorage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparestorage',
            name='barcode',
            field=models.CharField(default='5', max_length=255),
            preserve_default=False,
        ),
    ]
