# Generated by Django 5.0 on 2023-12-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_rename_material_sparestoragehistory_spare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparestorage',
            name='is_active',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('pending', 'Kutilmoqda')], default='active', max_length=8, verbose_name='Holati'),
        ),
    ]
