# Generated by Django 5.0 on 2023-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_sparestorage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='amount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='materialstoragehistory',
            name='amount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sparestoragehistory',
            name='amount',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
