# Generated by Django 5.0 on 2023-12-25 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_alter_labelstorage_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(default=1, max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('season', models.CharField(choices=[('winter', 'Qishki'), ('summer', 'Yozgi')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DesignField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0', max_length=255)),
                ('design_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.design')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='DesignImmutable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calc_type', models.CharField(choices=[('percent', 'Foiz'), ('sum', "So'm")], max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.design')),
            ],
        ),
        migrations.CreateModel(
            name='DesignLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.design')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.labeltype')),
            ],
        ),
    ]
