# Generated by Django 5.0 on 2023-12-27 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_design_designfield_designimmutable_designlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmutableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('calc_type', models.CharField(choices=[('percent', 'Foiz'), ('sum', "So'm")], max_length=255)),
                ('cost', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
