# Generated by Django 5.0 on 2023-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_immutablebalance_design_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_currency', models.CharField(default=0, max_length=255)),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
