# Generated by Django 5.0 on 2023-12-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designfield',
            name='design_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.design'),
        ),
        migrations.AlterField(
            model_name='designfield',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialtype'),
        ),
        migrations.AlterField(
            model_name='designlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.labeltype'),
        ),
    ]
