# Generated by Django 5.0 on 2023-12-28 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_alter_designfield_design_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_amount', models.CharField(default=0, max_length=255)),
                ('per_amount', models.CharField(default=0, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('sold', 'Sotilgan')], max_length=20)),
                ('sort_type', models.CharField(choices=[('second', 'Ikkinchi sort'), ('third', 'Uchinchi sort')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.design')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0', max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('comment', models.CharField(default='Izoh qoldiring', max_length=255)),
                ('is_active', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('pending', 'Kutilmoqda')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.design')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Kirim'), ('export', 'Chiqim'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('cancel', 'Bekor qilish'), ('sold', 'Sotish'), ('confirm', 'Tasdiqlash')], max_length=9)),
                ('amount', models.CharField(default='0', max_length=255)),
                ('amount_type', models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('kg', 'Kilogramm'), ('point', 'Dona'), ('meter', 'Metr')], default='point', max_length=5)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=5)),
                ('where', models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('production', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.production')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMaterialStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=0, max_length=600)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=3)),
                ('amount', models.CharField(max_length=255)),
                ('is_active', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('pending', 'Kutilmoqda')], default='pending', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.materialstorage')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMaterialStorageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Kirim'), ('export', 'Chiqim'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('cancel', 'Bekor qilish'), ('sold', 'Sotish'), ('confirm', 'Tasdiqlash')], max_length=9)),
                ('amount', models.CharField(default='0', max_length=255)),
                ('amount_type', models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('kg', 'Kilogramm'), ('point', 'Dona'), ('meter', 'Metr')], default='point', max_length=5)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=5)),
                ('where', models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('production', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.productionmaterialstorage')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionWorkerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.productionworker')),
            ],
        ),
    ]
