# Generated by Django 5.0 on 2023-12-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_productionworker_brak_production_productionhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelstoragehistory',
            name='where',
            field=models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('production', 'Ishlab chiqarish'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('product', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16),
        ),
        migrations.AlterField(
            model_name='materialstoragehistory',
            name='where',
            field=models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('production', 'Ishlab chiqarish'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('product', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16),
        ),
        migrations.AlterField(
            model_name='productionhistory',
            name='where',
            field=models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('production', 'Ishlab chiqarish'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('product', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16),
        ),
        migrations.AlterField(
            model_name='productionmaterialstoragehistory',
            name='where',
            field=models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('production', 'Ishlab chiqarish'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('product', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16),
        ),
        migrations.AlterField(
            model_name='sparestoragehistory',
            name='where',
            field=models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('production', 'Ishlab chiqarish'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('product', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16),
        ),
    ]
