# Generated by Django 5.0 on 2023-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_expenditurecategories_expenditure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExpenditureCategories',
        ),
    ]
