# Generated by Django 5.0 on 2023-12-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_expenditure_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('administration', 'Mamuriyat'), ('master', 'Usta'), ('tailor', 'Tikuvchi'), ('rosso_tailor', 'Rosso tikuvchisi'), ('turner', 'Ag`daruvchi'), ('moulder', 'Qolipchi'), ('charioteer', 'Arava yechuvchi'), ('taster', 'Tahlovchi'), ('label_setter', 'Etiketika uruvchi'), ('packer', 'Qadoqchi')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(default=0, max_length=255)),
                ('salary_types', models.CharField(choices=[('daily', 'Donabay'), ('monthly', 'Oylik'), ('per_way', 'Aravabay')], max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('car_number', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('cost', models.CharField(default=0, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.CharField(default=0, max_length=255)),
                ('debits', models.CharField(default=0, max_length=255)),
                ('fines', models.CharField(default=0, max_length=255)),
                ('workerworks_cost', models.CharField(default=0, max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.worker')),
                ('credits_history', models.ManyToManyField(blank=True, null=True, to='materials.workercredit')),
                ('debits_history', models.ManyToManyField(blank=True, null=True, to='materials.workerdebit')),
                ('fines_history', models.ManyToManyField(blank=True, null=True, to='materials.workerfine')),
                ('workerworks_history', models.ManyToManyField(blank=True, null=True, to='materials.workerwork')),
            ],
        ),
    ]
