# Generated by Django 5.0 on 2023-12-29 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_worker_workercredit_workerdebit_workerfine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmaterialstoragehistory',
            name='production_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialtype'),
        ),
    ]
