# Generated by Django 5.0 on 2023-12-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0030_alter_productionhistory_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(default='0', max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('credit', 'Chiqim'), ('debit', 'Kirim')], default='credit', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
