# Generated by Django 5.0 on 2024-01-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0032_finance_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='cost',
            field=models.CharField(default='0', max_length=255, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('credit', 'Chiqim'), ('debit', 'Kirim')], default='credit', max_length=16, verbose_name='Kirim / Chiqim'),
        ),
    ]
