# Generated by Django 5.0 on 2024-01-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_alter_finance_comment_alter_finance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='price_type',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=5),
        ),
    ]
