# Generated by Django 5.0 on 2024-01-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0034_finance_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='price_type',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=5, verbose_name='Pul birligi'),
        ),
    ]
