# Generated by Django 5.0 on 2024-01-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_alter_finance_price_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=0, max_length=600)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=3)),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.labelstorage')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.materialstorage')),
                ('spare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.sparestorage')),
            ],
        ),
        migrations.CreateModel(
            name='PreProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Kirim'), ('export', 'Chiqim'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('cancel', 'Bekor qilish'), ('sold', 'Sotish'), ('confirm', 'Tasdiqlash')], max_length=15)),
                ('amount', models.CharField(default='0', max_length=255)),
                ('amount_type', models.CharField(choices=[('gram', 'Gramm'), ('liter', 'Litr'), ('kg', 'Kilogramm'), ('point', 'Dona'), ('meter', 'Metr')], default='point', max_length=5)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('price_type', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=5)),
                ('where', models.CharField(choices=[('null', '--------'), ('material', 'Homashyo ombori'), ('label', 'Etiketika ombori'), ('production', 'Ishlab chiqarish'), ('spare', 'Ehtiyot qism ombori'), ('yaim', 'Yarim tayyor mahsulot'), ('product', 'Tayyor mahsulot ombori'), ('storage', 'Mahsulot ombori')], default='null', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.production')),
            ],
        ),
    ]
