# Generated by Django 5.0 on 2024-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0039_productsalescard_productsaleshistory_productstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
