# Generated by Django 4.2 on 2024-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0044_remove_productstock_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='price_type',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=255),
        ),
    ]
