# Generated by Django 4.2 on 2024-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0045_alter_productstock_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=255)),
                ('weight', models.CharField(default='0', max_length=16)),
                ('labels', models.CharField(default='0', max_length=16)),
                ('expense', models.CharField(default='0', max_length=16)),
                ('building', models.CharField(default='0', max_length=16)),
                ('machine', models.CharField(default='0', max_length=16)),
                ('invalid', models.CharField(default='0', max_length=16)),
                ('another_percent', models.CharField(default='0', max_length=16)),
                ('total', models.CharField(default='0', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='another_percent',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='building',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='expense',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='invalid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='labels',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='machine',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='total',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='design',
            name='weight',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
