# Generated by Django 4.2 on 2024-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0046_designpricehistory_design_another_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpricehistory',
            name='exchange',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
