# Generated by Django 4.2 on 2024-01-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0047_designpricehistory_design_another_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='sex',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('young', "O'smin"), ('baby', 'Bola')], max_length=10),
        ),
    ]
