# Generated by Django 4.2 on 2024-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0050_alter_design_another_percent_alter_design_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='another_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='building',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='machine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='materials',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='design',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
