# Generated by Django 4.2 on 2024-01-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0052_alter_design_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='materials',
            field=models.FloatField(default=0),
        ),
    ]
