# Generated by Django 4.2 on 2024-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0053_alter_design_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsalescard',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsalescard',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsalescard',
            name='contract_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsalescard',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
