# Generated by Django 4.2 on 2024-01-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Savdo'), ('MATERIAL', 'Material'), ('SPARE', 'Ehtiyot qism'), ('DIRECTOR', 'Nazoratchi'), ('INACTIVE', 'Nofaol')], max_length=32),
        ),
    ]
